/*
 * Generated by gdbus-codegen 2.48.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __VINAY245BUS_H__
#define __VINAY245BUS_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.vinay245.GDBUS */

#define VINAY245_BUS_TYPE_GDBUS (vinay245_bus_gdbus_get_type ())
#define VINAY245_BUS_GDBUS(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), VINAY245_BUS_TYPE_GDBUS, vinay245BusGDBUS))
#define VINAY245_BUS_IS_GDBUS(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), VINAY245_BUS_TYPE_GDBUS))
#define VINAY245_BUS_GDBUS_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), VINAY245_BUS_TYPE_GDBUS, vinay245BusGDBUSIface))

struct _vinay245BusGDBUS;
typedef struct _vinay245BusGDBUS vinay245BusGDBUS;
typedef struct _vinay245BusGDBUSIface vinay245BusGDBUSIface;

struct _vinay245BusGDBUSIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_hello_client) (
    vinay245BusGDBUS *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_greeting);

};

GType vinay245_bus_gdbus_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *vinay245_bus_gdbus_interface_info (void);
guint vinay245_bus_gdbus_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void vinay245_bus_gdbus_complete_hello_client (
    vinay245BusGDBUS *object,
    GDBusMethodInvocation *invocation,
    const gchar *response);



/* D-Bus method calls: */
void vinay245_bus_gdbus_call_hello_client (
    vinay245BusGDBUS *proxy,
    const gchar *arg_greeting,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean vinay245_bus_gdbus_call_hello_client_finish (
    vinay245BusGDBUS *proxy,
    gchar **out_response,
    GAsyncResult *res,
    GError **error);

gboolean vinay245_bus_gdbus_call_hello_client_sync (
    vinay245BusGDBUS *proxy,
    const gchar *arg_greeting,
    gchar **out_response,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define VINAY245_BUS_TYPE_GDBUS_PROXY (vinay245_bus_gdbus_proxy_get_type ())
#define VINAY245_BUS_GDBUS_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), VINAY245_BUS_TYPE_GDBUS_PROXY, vinay245BusGDBUSProxy))
#define VINAY245_BUS_GDBUS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), VINAY245_BUS_TYPE_GDBUS_PROXY, vinay245BusGDBUSProxyClass))
#define VINAY245_BUS_GDBUS_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), VINAY245_BUS_TYPE_GDBUS_PROXY, vinay245BusGDBUSProxyClass))
#define VINAY245_BUS_IS_GDBUS_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), VINAY245_BUS_TYPE_GDBUS_PROXY))
#define VINAY245_BUS_IS_GDBUS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), VINAY245_BUS_TYPE_GDBUS_PROXY))

typedef struct _vinay245BusGDBUSProxy vinay245BusGDBUSProxy;
typedef struct _vinay245BusGDBUSProxyClass vinay245BusGDBUSProxyClass;
typedef struct _vinay245BusGDBUSProxyPrivate vinay245BusGDBUSProxyPrivate;

struct _vinay245BusGDBUSProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  vinay245BusGDBUSProxyPrivate *priv;
};

struct _vinay245BusGDBUSProxyClass
{
  GDBusProxyClass parent_class;
};

GType vinay245_bus_gdbus_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (vinay245BusGDBUSProxy, g_object_unref)
#endif

void vinay245_bus_gdbus_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
vinay245BusGDBUS *vinay245_bus_gdbus_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
vinay245BusGDBUS *vinay245_bus_gdbus_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void vinay245_bus_gdbus_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
vinay245BusGDBUS *vinay245_bus_gdbus_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
vinay245BusGDBUS *vinay245_bus_gdbus_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define VINAY245_BUS_TYPE_GDBUS_SKELETON (vinay245_bus_gdbus_skeleton_get_type ())
#define VINAY245_BUS_GDBUS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), VINAY245_BUS_TYPE_GDBUS_SKELETON, vinay245BusGDBUSSkeleton))
#define VINAY245_BUS_GDBUS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), VINAY245_BUS_TYPE_GDBUS_SKELETON, vinay245BusGDBUSSkeletonClass))
#define VINAY245_BUS_GDBUS_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), VINAY245_BUS_TYPE_GDBUS_SKELETON, vinay245BusGDBUSSkeletonClass))
#define VINAY245_BUS_IS_GDBUS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), VINAY245_BUS_TYPE_GDBUS_SKELETON))
#define VINAY245_BUS_IS_GDBUS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), VINAY245_BUS_TYPE_GDBUS_SKELETON))

typedef struct _vinay245BusGDBUSSkeleton vinay245BusGDBUSSkeleton;
typedef struct _vinay245BusGDBUSSkeletonClass vinay245BusGDBUSSkeletonClass;
typedef struct _vinay245BusGDBUSSkeletonPrivate vinay245BusGDBUSSkeletonPrivate;

struct _vinay245BusGDBUSSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  vinay245BusGDBUSSkeletonPrivate *priv;
};

struct _vinay245BusGDBUSSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType vinay245_bus_gdbus_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (vinay245BusGDBUSSkeleton, g_object_unref)
#endif

vinay245BusGDBUS *vinay245_bus_gdbus_skeleton_new (void);


G_END_DECLS

#endif /* __VINAY245BUS_H__ */
